[credentials]
usernames = [
  { email = "admin@delicias.local",    name = "Admin",    password = "$2b$12$yfmF/pMBZJT2WYd5J5Jeyejaz42envloTvFt3XeQs0wAcGsfchRM." },
  { email = "cajero@delicias.local",   name = "Cajero",   password = "$2b$12$1Q81OCGRTGE7YueHPUYNiuBUinix7Pfnbt94s4V1mSsGkCUlsr.1q" },
  { email = "consulta@delicias.local", name = "Consulta", password = "$2b$12$FHsIUogQTrug20q.K0QzseQYuuJXAV0EWCvhQ6Ku5bqD7ITDbKWoi" }
]

[cookie]
name = "nomina_delicias_auth"
key = "Claveparacambiarcookies"
expiry_days = 7

[preauthorized]
emails = ["admin@delicias.local"]
